name: Deploy with terraform

on: push

permissions:
  contents: write
  id-token: write

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        - working-directory: ./infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::662147645652:role/deploy-terraform
          aws-region: eu-west-1
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
      - name: deploy terraform
        run: 
          terraform fmt
          terraform init
          terraform apply -auto-approve
      - name: destroy terraform
        run: 
          terraform destroy -auto-approve=true